# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a9608095946b607c24b95bda8d16a1ae10d3dee75fd17bb3d7bbc8cb3497b35e0aa3965dca6c05100738600f4ca6659932604529fa2e906b922f8f6b6e77ee

test:
  secret_key_base: de51bc8baaf9b65dae5941397edabe513f7584026df3db1a30c18d163faea1f820618b24b50f6762f6768933ef4e28a29c6a5069f4fc9fbf68bddea0d1be9c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
